### ISSUE TITLE
Enable Fork Pull Request Workflows

### ISSUE THREAD

**Issue by huyfififi** [mie-h/sprout#26]
#24 
#25

**Comment by mie-h** [comment]
Can you elaborate more on what to do?
I don't know what to do to enable fork pull request workflows.

**Comment by huyfififi** [comment]
@mie-h 

https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

Do you see any options on my pull request to approve workflow run?

**Comment by mie-h** [comment]
I don't see it

**Comment by mie-h** [comment]
<img width="1388" alt="Screenshot 2024-07-17 at 8 14 33 PM" src="https://github.com/user-attachments/assets/1219f450-4f08-46c7-af8f-27fd28057b7f">

**Comment by mie-h** [comment]
Resolving convs didn't help either
