### ISSUE TITLE
Increase readability of commit history

### ISSUE THREAD

**Issue by gomyway1216** [mie-h/sprout#58]
**Describe the bug**
I do see many commits that doesn't convey meaningful insights.
<img width="640" alt="Screenshot 2024-08-04 at 10 03 29 AM" src="https://github.com/user-attachments/assets/c0d7675a-5833-443e-978f-3cb3dac896dd">

**Expected behavior**
You could squash commits or try squash merge.

**Comment by huyfififi** [comment]
I prefer not to squash commits as long as they are not too redundant.
By keeping the history, I can follow the logical steps of others, and it's also easier to check information `git blame` (CLI & VSCode Extensions).
but my opinion might be biased

**Comment by huyfififi** [comment]
I also understand the advantage of squashing commits, cleaning the commit history, and making it easier to find a problematic commit using bisect. Either is fine with me.

**Comment by huyfififi** [comment]
@mie-h what do you think? Currently, rebase & merge is the only option

**Comment by mie-h** [comment]
I just enabled squash and merge option as well

**Comment by huyfififi** [comment]
@mie-h @LucileTech let's squash commits with little information or redundancy to maintain a clean commit history
