### ISSUE TITLE
Needs Error handling for chat api call

### ISSUE THREAD

**Issue by gomyway1216** [mie-h/sprout#59]
**Is your feature request related to a problem? Please describe.**
https://github.com/mie-h/sprout/blob/7415af7292d68ce4fda1576717e09b6de0545be0/frontend/src/app/page.tsx#L46
```
const res = await fetch("/api/chat", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ message }),
      });
```

Try refactoring this code by moving the API logic to a separate file. Each React component should ideally have a single responsibility, and handling API responses in the component layer goes against this principle.

**Describe the solution you'd like**

Create a New File for API Calls: Create a new file (e.g., api.js or api.ts) and move the API logic there. This file will export functions to fetch tasks and send messages.
Graceful Error Handling: Ensure error responses are handled gracefully in the new file. Instead of just printing and returning errors, provide meaningful feedback to the user, such as showing a notification or updating the UI to indicate a mistake.

Example of Refactoring: 
api.ts
```typescript
export const fetchTasks = async () => {
  const response = await fetch("/api/tasks");
  if (response.status === 401) {
    throw new Error("Unauthorized");
  }
  if (!response.ok) {
    throw new Error("Failed to fetch tasks");
  }
  return response.json();
};

export const sendMessage = async (message) => {
  const res = await fetch("/api/chat", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ message }),
  });

  const data = await res.json();
  if (!res.ok) {
    throw new Error(data.error || "Failed to send message");
  }
  return data.response;
};
```

frontend/src/app/page.tsx
```typescript
import { fetchTasks, sendMessage } from "@/api";  // Adjust the import path accordingly

useEffect(() => {
  (async () => {
    try {
      const tasks = await fetchTasks();
      setTasks(tasks);
    } catch (error) {
      if (error.message === "Unauthorized") {
        router.push("/login");
      } else {
        console.error("Error fetching tasks:", error);
        // Optionally update the UI to indicate an error
      }
    }
  })();
}, []);

const handleSendMessage = async (message) => {
  setMessages((prevMessages) => [
    ...prevMessages,
    { text: message, isSender: false },
  ]);

  try {
    const response = await sendMessage(message);
    setMessages((prevMessages) => [
      ...prevMessages,
      { text: response, isSender: true },
    ]);
  } catch (error) {
    console.error("Error sending message:", error);
    setMessages((prevMessages) => [
      ...prevMessages,
      { text: "Failed to process message", isSender: true },
    ]);
    // Optionally update the UI to indicate an error
  }
};
```

**Describe alternatives you've considered**
Consider using custom hooks to encapsulate some of this logic, which can further enhance code reuse and readability. For example, you could create a useFetchTasks hook to handle fetching tasks and managing state.

**Comment by huyfififi** [comment]
#68
